### ISSUE TITLE
Program halts on main_task: Calling app_main()

### ISSUE THREAD

**Issue by fahirad** [sengulhamza/esp32_st7789_lvgl#4]
Hello! 

I am just starting with Lvgl and ESP32 development, to be more specific, I am using esp32c3, I have cloned your master branch, I changed the pins according to my needs, however when I run your example the program stops (freezes) at line " main_task: Calling app_main() ", it doesn't restart, just halts there.
Do you know why that may be? 
Thanks in advance.

P.S. I have been able to run it with ESP32 WROOM 32U successfully, so I imagine it has something to do with target configuration, but I am not sure what exactly. Any help would be greatly appreciated. :)

**Comment by sengulhamza** [comment]
Hello @fahirad 

Would you try to get GPIO and SPI interface logs ? It might be a HAL layer configuration issue.
And then send log snippets here.

**Comment by fahirad** [comment]
Hi @sengulhamza ! Thanks a lot for such a fast response. 
I was able to start the program after all, quite honestly I wasn't sure what I messed up, but I think it may have been due to the fact that I changed multiple targets frequently. After I set my target, cleaned the project, reconfigured for debug and built it again, I was able to get it to work. 

Thanks in any case!

**Comment by sengulhamza** [comment]
Hi @fahirad,

I am glad to your problem was solved.

Have a great projects!
