### ISSUE TITLE
Partitions table

### ISSUE THREAD

**Issue by fahirad** [sengulhamza/esp32_st7789_lvgl#5]
Hi Hamza!

This is not really an issue but more of a question for discussion. I see that the project uses a custom partitions table with two spiffs partitions, yet I do not see that file system is used for anything, or am I missing something? 
Also why are they differentiated, one is "fs" and the other "www"? 

Thanks in advance.

**Comment by sengulhamza** [comment]
Hello @fahirad 

In fact, this is a preliminary preparation for a future feature.
It's related to flash encryption.
www is the partition reserved for the web server. You can learn the details from the issue I opened on esp-idf.

[https://github.com/espressif/esp-idf/issues/8959](https://github.com/espressif/esp-idf/issues/8959)


If you feel clear, please close the issue.
